- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- link:
    ~/.aprc:
    ~/.dotfiles: ''
    ~/.gitignore:
    ~/.gitconfig:
    ~/.git:
    ~/.shell:
    ~/.vim:
    ~/.vimrc:
    ~/.pryrc:
    ~/.oh-my-zsh/custom:
        glob: true
        path: oh-my-zsh/custom/*
    ~/.zshrc:
    ~/.rake: rake_global
    ~/.tmux.conf:
    ~/.tmuxline:
    ~/.ctags.d/default.ctags: 'ctags'
    ~/.config/nvim/init.vim: 'init.vim'
    ~/.config/nvim/coc-settings.json: 'coc-settings.json'
    ~/.config/solargraph/config.yml: 'solargraph.yml'
    ~/.config/nvim/UltiSnips:
      create: true
      glob: true
      path: snippets/ultisnips/*
    ~/.rgignore:

- shell:
    - git update-submodules
    -
      command: [./fonts/install.sh, Install fonts]
      stdin: true
      stdout: true
      stderr: true
