- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.gitignore:
    ~/.gitconfig:
    ~/.git:
    ~/.shell:
    ~/.vim:
    ~/.vimrc:
    ~/.pryrc:
    ~/.oh-my-zsh/custom:
        path: oh-my-zsh/custom
    ~/.oh-my-zsh/plugins/:
        glob: true
        path: oh-my-zsh/plugins/*
    ~/.oh-my-zsh/:
        glob: true
        path: oh-my-zsh/*.zsh
    ~/.zshrc:

- shell:
    - git update-submodules
    -
      command: [./fonts/install.sh, Install fonts]
      stdin: true
      stdout: true
      stderr: true
