---
- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.dotfiles: ""
    ~/.gitignore:
    ~/.gitconfig:
      force: true
      path: spin_env/gitconfig
    ~/.git:
    ~/.shell:
    ~/.vim:
    ~/.zsh:
    ~/.zshrc:
      force: true
    ~/.vimrc:
    ~/.pryrc:
    ~/.zshenv:
    ~/.rake: rake_global
    ~/.config/nvim/init.vim: "init.vim"
    ~/.config/nvim/coc-settings.json: "coc-settings.json"
    ~/.config/solargraph/config.yml: "solargraph.yml"
    ~/.config/nvim/UltiSnips:
      create: true
      glob: true
      path: snippets/ultisnips/*
    ~/.rgignore:
- shell:
    - [sudo add-apt-repository -y ppa:neovim-ppa/unstable]
    - [sudo apt-get update]
    - [sudo apt-get install -y neovim]
    - [zsh -i -c -- '@zinit-scheduler burst']
    - [source $HOME/.zshrc, Reloading zsh]
    - [nvim --headless -c "PlugInstall" +qall, Loading nvim plugins]
    - [nvim --headless -c 'CocInstall -sync coc-solargraph coc-json coc-rls coc-tsserver coc-yaml coc-highlight coc-lists coc-eslint|q' +qall, Loading Coc.vim Plugins]
