- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.dotfiles: ""
    ~/.gitignore:
      force: true
    ~/.gitconfig:
      force: true
    ~/.git:
    ~/.shell:
    ~/.vim:
    ~/.vimrc:
    ~/.pryrc:
    ~/.oh-my-zsh/custom:
      create: true
      force: true
      glob: true
      path: oh-my-zsh/custom/*
    ~/.zshenv:
    ~/.rake: rake_global
    ~/.config/nvim/init.vim: "init.vim"
    ~/.config/nvim/coc-settings.json: "coc-settings.json"
    ~/.config/solargraph/config.yml: "solargraph.yml"
    ~/.config/nvim/UltiSnips:
      create: true
      glob: true
      path: snippets/ultisnips/*
    ~/.config/omf:
      glob: true
      path: config/omf/*
    ~/.rgignore:
- shell:
    - [echo "source $HOME/dotfiles/zshrc" >> $HOME/.zshrc, Adding to existing zshrc]
    - [source $HOME/.zshrc, Reloading zsh]
    - [nvim --headless -c "PlugInstall" +qall, Loading nvim plugins]
    - [nvim --headless -c 'CocInstall -sync coc-solargraph coc-json coc-rls coc-tsserver coc-yaml coc-highlight coc-lists coc-eslint|q' +qall, Loading Coc.vim Plugins]
