---
- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.dotfiles: ""
    ~/.gitignore:
    ~/.gitconfig:
      force: true
      path: spin_env/gitconfig
    ~/.git:
    ~/.shell:
    ~/.vim:
    ~/.zsh:
    ~/.zshrc:
      force: true
    ~/.vimrc:
    ~/.pryrc:
    ~/.zshenv:
    ~/.rake: rake_global
    ~/.config/nvim/init.vim: "init.vim"
    ~/.config/nvim/coc-settings.json: "coc-settings.json"
    ~/.config/solargraph/config.yml: "solargraph.yml"
    ~/.config/nvim/UltiSnips:
      create: true
      glob: true
      path: snippets/ultisnips/*
    ~/.rgignore:

- shell:
    - [sudo apt remove neovim -y]
    - [zsh -i -c -- '@zinit-scheduler burst']
    - [source $HOME/.zshrc, Reloading zsh]
    - [sudo add-apt-repository -y ppa:neovim-ppa/unstable]
    - [sudo apt-get update]
    - [sudo apt-get install node]
    - [sudo apt-get install -y neovim]
    - [pip3 install --user neovim]
    - [sudo apt-get install -y python3-neovim]
    - [git clone https://github.com/junegunn/vim-plug.git "$HOME/vim-plug"]
    - [mkdir -p $HOME/.local/share/nvim/site/autoload]
    - [cp ~/vim-plug/plug.vim $HOME/.local/share/nvim/site/autoload]
    - [sudo apt-get install -y powerline fonts-powerline]
    - [nvim --headless -c "PlugInstall" +qall, Loading nvim plugins]
    - [nvim --headless -c 'CocInstall -sync coc-solargraph coc-json coc-rls coc-tsserver coc-yaml coc-highlight coc-lists coc-eslint|q' +qall, Loading Coc.vim Plugins]
